const content = [
  {
    "title": "\n      TERMS OF USE\n    ",
    "body": [
      "\n      These terms of use (\u201cTerms of Use\u201d or \u201cTerms\u201d) govern\n      your (\u201cYour\u201d or \u201cYou\u201d) use of our online interfaces and properties\n      (e.g., websites and mobile applications) owned and controlled by\n      Healiom, Inc. (\u201cHealiom\u201d or \u201cWe\u201d), including the www.healiom.com\n      website and telehealth platform (collectively, the \u201cSite\u201d) and the\n      services available to users through the Site (\u201cServices\u201d). Your\n      compliance with these Terms of Use is a condition to your use of the\n      Site. If you do not agree to be bound by the Terms of Use, promptly exit\n      this Site. Please also consult our Privacy Policy for a description of\n      our privacy practices and policies, including how we collect and handle\n      your personal health information and financial information. Please\n      review these Terms carefully before using the Services. We may change\n      these Terms or modify any features of the Services at any time. The most\n      current version of the Terms can be viewed by clicking on the \u201cTerms of\n      Use\u201d link. You accept these Terms by using the Services, and you accept\n      any changes to the Terms by continuing to use the Services after we post\n      the changes.\n    ",
      "Important Information about Your use of the Services",
      "\n      IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY, YOU SHOULD DIAL \u201c911\u201d\n      IMMEDIATELY.\n    ",
      "\n      Healiom does not provide any physicians' or other healthcare providers'\n      services itself. All of the providers are independent of Healiom and use\n      the Site as a way to communicate with you. All clinical services for\n      Healiom are provided by one or more Baker Street Medical Group (\u201cBaker\n      Street Medical Group\u201d) each an independent, physician-owned medical\n      group with a national network of United States-based licensed providers\n      who provide clinical telehealth services (collectively, the\n      \u201cProviders\u201d). Any information or advice received from a Provider comes\n      from the Provider alone, and not from Healiom Inc.. Your interactions\n      with the Providers via the Site are not intended to take the place of\n      your relationship with your regular health care practitioners. Neither\n      Healiom nor any of their subsidiaries or affiliates or any third party\n      who may promote the Services or provide a link to the Site, shall be\n      liable for any professional advice obtained from a Provider via the Site\n      or for any other information obtained on the Site. Healiom does not\n      endorse any specific tests, physicians, medications, products or\n      procedures that are recommended by Providers that may use the Site to\n      communicate with you. You acknowledge that your reliance on any\n      Providers or information provided by the Providers via the Site is\n      solely at your own risk and you assume full responsibility for all risk\n      associated herewith.\n    ",
      "\n      Healiom does not make any representations or warranties about the\n      training or skill of any Providers who provide services via the Site.\n    ",
      "\n      You hereby certify that you are physically located in the state you have\n      entered as your current location on the Site. You acknowledge that your\n      ability to access and use the Services is conditioned on the\n      truthfulness of this certification and that the Providers you access\n      through the Site are relying upon this certification in order to\n      interact with you. In the event that your certification is inaccurate,\n      you agree to indemnify Healiom and the Providers you interact with from\n      any resulting damages, costs, or claims.\n    "
    ]
  },
  {
    "title": "1. Ownership Of The Site And Related Materials",
    "body": [
      "\n      All pages within this Site and any material made available for download\n      are the property of Healiom, or its licensors or suppliers, as\n      applicable. The Site is protected by United States and international\n      copyright and trademark laws.\n    "
    ]
  },
  {
    "title": "2. Electronic Communications",
    "body": [
      "\n      When you use the Site, including sending e-mails, text messages, and\n      other communications from your desktop or mobile device to us, you are\n      communicating with us electronically. You consent to receive\n      communications from us electronically. You agree that (a) all agreements\n      and consents can be signed electronically and (b) all notices,\n      disclosures, and other communications that we provide to you\n      electronically satisfy any legal requirement that such notices and other\n      communications be in writing.\n    ",
      "\n      a. When you opt-in to the service, we will send you an SMS message to\n      confirm your signup.\n    ",
      "\n      b. After scheduling a consultation on the Healiom technology platform,\n      you will receive SMS messages with regards to your consultation status.\n    ",
      "\n      c. You can cancel the SMS service at any time. Just text \u201cSTOP\u201d to the\n      short code. After you send the SMS message \u201cSTOP\u201d to us, we will send\n      you an SMS message to confirm that you have been unsubscribed. After\n      this, you will no longer receive SMS messages from us. If you want to\n      join again, just sign up as you did the first time and we will start\n      sending SMS messages to you again.\n    ",
      "\n      d. If at any time you forget what keywords are supported, just text\n      \u201cHELP\u201d to the short code. After you send the SMS message \u201cHELP\u201d to us,\n      we will respond with instructions on how to use our service as well as\n      how to unsubscribe.\n    ",
      "\n      e. We are able to deliver messages to the following mobile phone\n      carriers: Major carriers: AT&T, Verizon Wireless, Sprint, T-Mobile,\n      MetroPCS, U.S. Cellular, Alltel, Boost Mobile, Nextel, and Virgin\n      Mobile. Minor carriers: Alaska Communications Systems (ACS), Appalachian\n      Wireless (EKN), Bluegrass Cellular, Cellular One of East Central IL\n      (ECIT), Cellular One of Northeast Pennsylvania, Cincinnati Bell\n      Wireless, Cricket, Coral Wireless (Mobi PCS), COX, Cross, Element Mobile\n      (Flat Wireless), Epic Touch (Elkhart Telephone), GCI, Golden State,\n      Hawkeye (Chat Mobility), Hawkeye (NW Missouri), Illinois Valley\n      Cellular, Inland Cellular, iWireless (Iowa Wireless), Keystone Wireless\n      (Immix Wireless/PC Man), Mosaic (Consolidated or CTC Telecom), Nex-Tech\n      Wireless, NTelos, Panhandle Communications, Pioneer, Plateau (Texas RSA\n      3 Ltd), Revol, RINA, Simmetry (TMP Corporation), Thumb Cellular, Union\n      Wireless, United Wireless, Viaero Wireless, and West Central (WCC or 5\n      Star Wireless). ***Carriers are not liable for delayed or undelivered\n      messages***\n    ",
      "\n      f. As always, message and data rates may apply for any messages sent to\n      you from us and to us from you. You will receive varied frequency of\n      messages. If you have any questions about your text plan or data plan,\n      it is best to contact your wireless provider. For all questions about\n      the services provided by this short code, you can send an email to\n      support@healiom.com\n    ",
      "\n      g. If you have any questions regarding privacy, please read our privacy\n      policy: compliance@bakerstreetmedicalgroup.com\n    "
    ]
  },
  {
    "title": "3. Site Access, Security and Restrictions; Passwords",
    "body": [
      "\n      If you create a subscriber account for the Healiom Site, you agree to\n      complete the registration process by providing current, complete, and\n      accurate information as required by Healiom. You are responsible for all\n      activities that occur under your account. In the event access to the\n      Site or a portion thereof is limited requiring a user ID and password\n      (\u201cProtected Areas\u201d), you agree to access Protected Areas using only your\n      user ID and password as provided to you by Healiom. You agree to protect\n      the confidentiality of your user ID and password, and not to share or\n      disclose your user ID or password to any third party. You agree that you\n      are fully responsible for all activity occurring under your user ID.\n      Your access to the Site may be revoked by Healiom at any time with or\n      without cause.\n    ",
      "\n      You are prohibited from violating or attempting to violate the security\n      of the Site, including, without limitation, (a) accessing data not\n      intended for such user or logging onto a server or an account which the\n      user is not authorized to access; or (b) attempting to probe, scan or\n      test the vulnerability of a system or network or to breach security or\n      authentication measures without proper authorization; or (c) accessing\n      or using the Site or any portion thereof without authorization, in\n      violation of these Terms of Use or in violation of applicable law. If\n      you are under 18, you may use the Healiom Services only with involvement\n      of a parent or guardian.\n    ",
      "\n      You may not use any scraper, crawler, spider, robot or other automated\n      means of any kind to access or copy data on the Site, deep-link to any\n      feature or content on the Site, bypass our robot exclusion headers or\n      other measures we may use to prevent or restrict access to the Site.\n      Violations of system or network security may result in civil or criminal\n      liability. Healiom will investigate occurrences that may involve such\n      violations and may involve, and cooperate with, law enforcement\n      authorities in prosecuting users who are involved in such violations.\n      You agree not to use any device, software or routine to interfere or\n      attempt to interfere with the proper working of this Site or any\n      activity being conducted on this Site.\n    "
    ]
  },
  {
    "title": "4. No Medical Advice or Services",
    "body": [
      "\n      Baker Street Medical Group provides clinical services through the Site\n      and mobile application. Baker Street Medical Group is an independent,\n      physician-owned medical group with a national network of United States\n      based Providers who provide clinical telehealth services. Baker Street\n      Medical Group provides clinical services via the Healiom, Inc. website\n      and or mobile app for Healiom Inc. customers.\n    ",
      "\n      IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY, YOU SHOULD DIAL \u201c911\u201d\n      IMMEDIATELY.\n    ",
      "\n      THE CONTENT OF THE SITE AND THE SERVICES, INCLUDING WITHOUT LIMITATION,\n      TEXT, COPY, AUDIO, VIDEO, PHOTOGRAPHS, ILLUSTRATIONS, GRAPHICS AND OTHER\n      VISUALS, IS FOR INFORMATIONAL PURPOSES ONLY AND DOES NOT CONSTITUTE\n      PROFESSIONAL MEDICAL ADVICE, DIAGNOSIS, TREATMENT OR RECOMMENDATIONS OF\n      ANY KIND. YOU SHOULD ALWAYS SEEK THE ADVICE OF YOUR QUALIFIED HEALTHCARE\n      PROFESSIONALS WITH ANY QUESTIONS OR CONCERNS YOU MAY HAVE REGARDING YOUR\n      INDIVIDUAL NEEDS AND ANY MEDICAL CONDITIONS. ALL INFORMATION PROVIDED BY\n      HEALIOM OR IN CONNECTION WITH ANY COMMUNICATIONS SUPPORTED BY HEALIOM,\n      INCLUDING BUT NOT LIMITED TO COMMUNICATIONS WITH HEALIOM MEDICAL EXPERTS\n      IS INTENDED TO BE FOR GENERAL INFORMATIONAL PURPOSES ONLY, AND IS IN NO\n      WAY INTENDED TO CREATE A PHYSICIAN - PATIENT RELATIONSHIP AS DEFINED BY\n      STATE AND FEDERAL LAW. THE SITE AND SERVICES ARE NOT A SUBSTITUTE FOR\n      PROFESSIONAL MEDICAL DIAGNOSIS OR TREATMENT. RELIANCE ON ANY INFORMATION\n      APPEARING ON THE SITE, WHETHER PROVIDED BY HEALIOM, ITS CONTENT\n      PROVIDERS, MEDICAL EXPERTS, CLIENTS, VISITORS TO THE SITE OR OTHERS, IS\n      SOLELY AT YOUR OWN RISK. WHILE HEALIOM FACILITATES YOUR SELECTION OF,\n      COMMUNICATIONS WITH AND OTHER INTERACTIONS WITH PHYSICIANS, HEALIOM DOES\n      NOT PROVIDE MEDICAL SERVICES AND THE DOCTOR-PATIENT RELATIONSHIP IS\n      BETWEEN YOU AND THE HEALTHCARE PROVIDER YOU SELECT. ALL HEALTHCARE\n      PROVIDERS IDENTIFIED OR ACCESSIBLE ON THE SITE ARE INDEPENDENT PROVIDERS\n      AND ARE NOT EMPLOYED BY OR AFFILIATED WITH HEALIOM.\n    "
    ]
  },
  {
    "title": "5. License And Access",
    "body": [
      "\n      Subject to your compliance with these Terms of Use and your payment of\n      any applicable fees, Healiom or its content providers grant you a\n      limited, non-exclusive, non-transferable, non-sub-licensable license to\n      access and make personal and non-commercial use of the Healiom Services.\n      This license does not include any resale or commercial use of any\n      Healiom Service, or its contents; any collection and use of any service\n      listings, descriptions, or prices; any derivative use of any Healiom\n      Service or its contents; any downloading, copying, or other use of\n      account information for the benefit of any third party; or any use of\n      data mining, robots, or similar data gathering and extraction tools. All\n      rights not expressly granted to you in these Terms of Use are reserved\n      and retained by Healiom or its licensors, suppliers, publishers, rights\n      holders, or other content providers. No Healiom Service, nor any part of\n      any Healiom Service, may be reproduced, duplicated, copied, sold,\n      resold, visited, or otherwise exploited for any commercial purpose\n      without express written consent of Healiom. You may not frame or utilize\n      framing techniques to enclose any trademark, logo, or other proprietary\n      information (including images, text, page layout, or form) of Healiom\n      without express written consent. You may not use any meta tags or any\n      other \u201chidden text\u201d utilizing Healiom's name or trademarks without the\n      express written consent of Healiom. You may not misuse the Healiom\n      Services. You may use the Healiom Services only as permitted by law. The\n      licenses granted by Healiom terminate if you do not comply with these\n      Terms of Use.\n    ",
      "\n      The Contents of the Site, including without limitation the files,\n      documents, text, photographs, images, audio, and video, and any\n      materials accessed through or made available for use or download through\n      this Site (\u201cContent\u201d) may not be copied, distributed, modified,\n      reproduced, published or used, in whole or in part, except for purposes\n      authorized or approved in writing by Healiom. You may not frame or\n      utilize framing techniques to enclose, or deep linking to, any name,\n      trademarks, service marks, logo, Content or other proprietary\n      information (including; images, text, page layout, or form) of Healiom\n      without our express written consent.\n    "
    ]
  },
  {
    "title": "6. Accuracy and Integrity of Information",
    "body": [
      "\n      Although Healiom attempts to ensure the integrity and accuracy of the\n      Site, it makes no representations, warranties or guarantees whatsoever\n      as to the correctness or accuracy of the Site and Content thereon. It is\n      possible that the Site could include typographical errors, inaccuracies\n      or other errors, and that unauthorized additions, deletions and\n      alterations could be made to the Site by third parties. In the event\n      that an inaccuracy arises, please inform Healiom so that it can be\n      corrected. Information contained on the Site may be changed or updated\n      without notice. Additionally, Healiom shall have no responsibility or\n      liability for information or Content posted to the Site from any\n      non-Healiom affiliated third party.\n    "
    ]
  },
  {
    "title": "7. Links to Other Sites",
    "body": [
      "\n      Healiom makes no representations whatsoever about any other website that\n      you may access through this Site. When you access a non-Healiom site,\n      please understand that it is independent from Healiom, and that Healiom\n      has no control over the Content on that website. In addition, a link to\n      a non-Healiom website does not mean that Healiom endorses or accepts any\n      responsibility for the Content, or the use, of the linked site. It is up\n      to you to take precautions to ensure that whatever you select for your\n      use or download is free of such items as viruses, worms, Trojan horses,\n      and other items of a destructive nature. If you decide to access any of\n      the third party sites linked to this Site, you do this entirely at your\n      own risk.\n    "
    ]
  },
  {
    "title": "8. User Information",
    "body": [
      "\n      If you submit, upload, post or transmit any health information, medical\n      history, conditions, problems, symptoms, personal information, consent\n      forms, agreements, requests, comments, ideas, suggestions, information,\n      files, videos, images or other materials to us or our Site (\u201cUser\n      Information\u201d), you agree not to provide any User Information that (1) is\n      false, inaccurate, defamatory, abusive, libelous, unlawful, obscene,\n      threatening, harassing, fraudulent, pornographic, or harmful, or that\n      could encourage criminal or unethical behavior, (2) violates or\n      infringes the privacy, copyright, trademark, trade dress, trade secrets\n      or intellectual property rights of any person or entity, or (3) contains\n      or transmits a virus or any other harmful component. You agree not to\n      contact other site users through unsolicited e-mail, telephone calls,\n      mailings or any other method of communication. You represent and warrant\n      to Healiom and its Providers that you have the legal right and\n      authorization to provide all User Information to Healiom and its\n      Providers for use as set forth herein and required by Healiom and the\n      Provider.\n    "
    ]
  },
  {
    "title": "9. Claims of Copyright Infringement",
    "body": [
      "\n      We disclaim any responsibility or liability for copyrighted materials\n      posted on our site. If you believe that your work has been copied in a\n      manner that constitutes copyright infringement, please follow the\n      procedures set forth below.\n    ",
      "\n      Healiom respects the intellectual property rights of others and expects\n      its users to do the same. In accordance with the Digital Millennium\n      Copyright Act (\u201cDMCA\u201d), we will respond promptly to notices of alleged\n      infringement that are reported to Healiom's Designated Copyright Agent,\n      identified below.\n    ",
      "\n      Notices of Alleged Infringement for Content Made Available on the Site\n    ",
      "\n      If you are a copyright owner, authorized to act on behalf of one, or\n      authorized to act under any exclusive right under copyright, please\n      report alleged copyright infringements taking place on or through our\n      Site by sending us a notice (\u201cNotice\u201d) complying with the following\n      requirements.\n    ",
      "Identify the copyrighted works that you claim have been infringed.",
      "\n      Identify the material or link you claim is infringing (or the subject of\n      infringing activity) and that access to which is to be disabled,\n      including at a minimum, if applicable, the URL of the link shown on the\n      Site where such material may be found. Provide your mailing address,\n      telephone number, and, if available, email address both of the following\n      statements in the body of the Notice: \u201cI hereby state that I have a good\n      faith belief that the disputed use of the copyrighted material is not\n      authorized by the copyright owner, its agent, or the law (e.g., as a\n      fair use).\u201d\n    ",
      "\n      \u201cI hereby state that the information in this Notice is accurate and,\n      under penalty of perjury, that I am the owner, or authorized to act on\n      behalf of the owner, of the copyright or of an exclusive right under the\n      copyright that is allegedly infringed. \u201dProvide your full legal name and\n      your electronic or physical signature. Deliver this Notice, with all\n      items completed, to compliance@bakerstreetmedicalgroup.com\n    "
    ]
  },
  {
    "title": "10. Disclaimer of Warranties",
    "body": [
      "\n      YOUR USE OF THE SERVICES IS AT YOUR OWN RISK. THE SERVICES ARE PROVIDED\n      \u201cAS IS\u201d WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,\n      INCLUDING WITHOUT LIMITATION WARRANTIES OF TITLE, MERCHANTABILITY,\n      PARTICULAR PURPOSE, NON-INFRINGEMENT, OR OTHER VIOLATION OF RIGHTS. WE\n      DO NOT WARRANT THE ADEQUACY, CURRENCY, ACCURACY, LIKELY RESULTS, OR\n      COMPLETENESS OF THE SERVICES OR ANY THIRD-PARTY SITES LINKED TO OR FROM\n      THE SERVICES, OR THAT THE FUNCTIONS WILL BE UNINTERRUPTED, VIRUS-FREE,\n      OR ERROR-FREE. WE EXPRESSLY DISCLAIM ANY LIABILITY FOR ANY ERRORS OR\n      OMISSIONS IN THE CONTENT INCLUDED IN THE SERVICES OR ANY THIRTY- PARTY\n      SITES LINKED TO OR FROM THE SERVICES. SOME JURISDICTIONS MAY NOT ALLOW\n      THE EXCLUSION OF IMPLIED WARRANTIES, SO SOME OF THE ABOVE EXCLUSIONS MAY\n      NOT APPLY TO YOU.\n    ",
      "\n      In no event will Healiom or its parents, subsidiaries, affiliates,\n      licensors, suppliers and their directors, officers, trustees,\n      affiliates, subcontractors, employees, agents, and assigns be liable for\n      any direct or indirect, special, incidental, consequential or punitive\n      damages, lost profits, or other damages whatsoever arising in connection\n      with the use of the Site or provision of Services, any interruption in\n      availability of the Services, delay in operation or transmission,\n      computer virus, loss of data, or use, misuse, reliance, review,\n      manipulation, or other utilization in any manner whatsoever of the\n      Services or the data collected through the Services, even if one or more\n      of them has been advised of the possibility of such damages or loss.\n      BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF\n      INCIDENTAL OR CONSEQUENTIAL DAMAGES, LIABILITY IN SUCH JURISDICTIONS\n      SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.\n    ",
      "\n      You agree that your sole remedy for any claim arising out of or\n      connected with the Services will be to cease using the Services.\n    ",
      "\n      You acknowledge and agree that Healiom is not engaged in the practice of\n      medicine and that Healiom is not determining appropriate medical use of\n      the Services. Healiom and any licensors, suppliers, or third parties who\n      promote the Services or provide you with a link to the Services\n      expressly disclaim any and all liability resulting from the delivery of\n      healthcare via the Site, including but not limited to professional\n      liability.\n    "
    ]
  },
  {
    "title": "11. Indemnification",
    "body": [
      "\n      You agree to indemnify, defend and hold Healiom and its parents,\n      subsidiaries, affiliates, licensors, suppliers and their directors,\n      officers, trustees, affiliates, subcontractors, employees, agents, and\n      assigns harmless from and against any and all loss, costs, expenses\n      (including reasonable attorneys\u2019 fees and expenses), claims, damages and\n      liabilities related to or associated with your use of the Services and\n      any alleged violation by you of these Terms, violation of applicable\n      law, or access by anyone accessing the Site using your user ID and\n      password. Healiom reserves the right to assume the exclusive defense of\n      any claim for which either or both are entitled to indemnification under\n      this section. In such an event, you shall provide us with such\n      cooperation as we reasonably request.\n    "
    ]
  },
  {
    "title": "12. Dispute Resolution.",
    "body": [
      "\n      Healiom will strive to work in good faith to resolve any issue you have\n      with the Site, including services ordered or purchased through the Site,\n      if you bring that issue to the attention of our customer service\n      department. However, we realize that there may be rare cases where we\n      may not be able to resolve an issue to a customer's satisfaction. In the\n      event we cannot resolve a dispute between us, you agree that all matters\n      related to any use or access of the Site, the Services or any other\n      Healiom site will be governed by the laws of the State of Delaware,\n      without regard to its conflicts of laws rules. You hereby waive any\n      objections to such jurisdiction or venue. Any claims or controversies\n      arising out of this Agreement, and/or the related use and access of the\n      Site, the Services or any other Healiom site.\n    "
    ]
  },
  {
    "title": "13. Force Majeure",
    "body": [
      "\n      We will not be deemed to be in breach of these terms or liable for any\n      breach of these terms or our privacy policy due to any event or\n      occurrence beyond our reasonable control, including without limitation,\n      acts of God, terrorism, war, invasion, failures of any public networks,\n      electrical shortages, earthquakes or floods, civil disorder, strikes,\n      fire or other disaster.\n    "
    ]
  },
  {
    "title": "14. Right to Modify Revisions; General",
    "body": [
      "\n      Healiom reserves the right to modify these Terms of Use at any time,\n      effective upon posting. Any use of this website after such changes will\n      be deemed an acceptance of those changes. You agree to review the Terms\n      of Use each time you access this website so that you may be aware of any\n      changes to these Terms. Healiom uses Google Analytics, a third-party\n      tracking service, which uses cookies to track non-personal identifiable\n      information about our visitors to our main site in the aggregate to\n      capture usage and volume statistics. Healiom has no access to or control\n      over these cookies. The companion Privacy Policy covers the use of\n      cookies by Healiom only and does not cover the use of cookies by any\n      third-party. Healiom reserves the right, in its sole discretion, to\n      terminate your access to all or part of this Site, with or without\n      cause, and with or without notice. In the event that any of the Terms of\n      Use are held by a court or other tribunal of competent jurisdiction to\n      be unenforceable, such provisions shall be limited or eliminated to the\n      minimum extent necessary so that these Terms of Use shall otherwise\n      remain in full force and effect. These Terms of Use constitute the\n      entire agreement between Healiom and you pertaining to the subject\n      matter hereof. In its sole discretion, Healiom may from time-to-time\n      revise these Terms of Use by updating this posting. You should,\n      therefore, periodically visit this page to review the current Terms of\n      Use, so you are aware of any such revisions to which you are bound.\n      Certain provisions of these Terms of Use may be superseded by expressly\n      designated legal notices or terms located on particular pages within\n      this Site.\n    ",
    ]
  }
]

export default content;